on:
  push:
  pull_request:

name: Build aarch64

jobs:
  build:
    name: Build
    runs-on: self-hosted
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
    steps:
      - uses: actions/checkout@v2
      - name: Setup homebrew
        run: |
          echo "/opt/homebrew/bin" >> "${GITHUB_PATH}"
          echo "/opt/homebrew/sbin" >> "${GITHUB_PATH}"
      - name: Install crosstool-ng
        run: |
          brew install coreutils
          brew install --HEAD crosstool-ng
      - name: Mount volumes
        run: |
          hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 16g -volname build build.dmg
          hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 1g -volname tools tools.dmg
          hdiutil attach build.dmg.sparseimage
          hdiutil attach tools.dmg.sparseimage
          ls /Volumes
      - name: Build Toolchain
        run: |
          mkdir /Volumes/build/src
          cd ${{ matrix.target }}
          arch -arm64 ct-ng build
      - name: Archive Toolchain
        run: |
          cd /Volumes/tools
          tar czf ${{ matrix.target }}-aarch64-darwin.tar.gz ${{ matrix.target }}
          cd -
          mv /Volumes/tools/${{ matrix.target }}-aarch64-darwin.tar.gz .
      - name: Remove volumes
        run: |
          hdiutil detach /Volumes/build
          hdiutil detach /Volumes/tools
      - name: Upload Toolchain
        uses: actions/upload-artifact@v2
        with:
          name: toolchains
          path: ${{ matrix.target }}-aarch64-darwin.tar.gz
      - name: Upload Toolchain to GitHub Release
        uses: svenstaro/upload-release-action@v2
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: ${{ matrix.target }}-aarch64-darwin.tar.gz
          file: ${{ matrix.target }}-aarch64-darwin.tar.gz
          tag: ${{ github.ref }}
